theme: jekyll-theme-cayman
url: https://datatalks.club
google_analytics: G-7NPZ94MHEC
name: DataTalks.Club
twitter: '@DataTalksClub'
permalink: /blog/:title.html

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
  - previews/


collections:
  books:
    output: true
  people:
    output: true


defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"