theme: jekyll-theme-cayman
url: https://datatalks.club
google_analytics: G-7NPZ94MHEC
name: DataTalks.Club
twitter: '@DataTalksClub'
permalink: /blog/:title.html

collections:
  people:
    output: true

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "author"