theme: jekyll-theme-cayman
url: https://datatalks.club
google_analytics: G-7NPZ94MHEC
name: DataTalks.Club
twitter: '@DataTalksClub'
permalink: /blog/:title.html

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
  - previews/
  - scripts/
  - env/


collections:
  books:
    output: true
    permalink: /:collection/:title.html
  people:
    output: true
    permalink: /:collection/:title.html
  conferences:
    output: true
    permalink: /:collection/:title.html
  podcast:
    output: true
    permalink: /:collection/:title.html

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "podcast"
    values:
      layout: "podcast"
