name: generate_post_doc
on:
  push:
    paths:
      - '_docx/*.docx'
jobs:
  generate_all:
    runs-on: "ubuntu-latest"
    steps:
      - name: install chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser libxss1 \
              fonts-ipafont-gothic fonts-wqy-zenhei \
              fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
              --no-install-recommends
      - run: chromium-browser --version
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: pipenv install
        run: |
          pip install pipenv
          pipenv install
      - name: npm install
        run: |
          (cd previews && \
            PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install)
      - name: install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb -O pandoc.deb
          sudo dpkg -i pandoc.deb
          rm pandoc.deb
      - name: Generate files
        id: generate
        env:
          REMOVE_DOC: True
        run: |
          sudo ln -s `which bash` /bin/gitbash

          for FILE in ${{ steps.files.outputs.all }}; do
            pipenv run python scripts/pandoc_full.py ${FILE}
          done
      - uses: EndBug/add-and-commit@v8
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          assignees: alexeygrigorev
          commit-message: "Post: ${{ steps.generate.outputs.post-id}}"
          title: "Post: ${{ github.event.issue.title }}"

        