name: generate_all
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
    #
jobs:
  generate_all:
    runs-on: "ubuntu-latest"
    steps:
      - name: install chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser libxss1 \
              fonts-ipafont-gothic fonts-wqy-zenhei \
              fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
              --no-install-recommends
      - run: chromium-browser --version
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
      - run: |
          pip install pipenv
          pipenv install
      - run: ls